### ISSUE TITLE
OpenAI Structured Outputs and DateTime

### ISSUE THREAD

**Issue by nickknyc** [ontolocy/neontology#31] opened 2024-09-13 14:43 UTC
Hi

The package is really helpful. Am running into one issue. 

It seems that BaseNode has two datetime fields, created and merged. I understand the function in neo4j, but when I try to include OpenAI into the process using Structured Outputs, the call fails because OpenAI Structured Outputs does not support datetime. 

Can the "created" and "merged" fields be changed to strings and use the ISO 8601 standard representation?

Otherwise, do you have any ideas on how I can exclude the "created" and "merged" fields without creating a new subclass or creating one dynamically? 

Am trying to keep things as simple and consistent as possible
https://platform.openai.com/docs/guides/structured-outputs

**Comment by hardchor** [comment] 2024-09-16 17:17
Hey!

I don't think there is much of an issue with building your own base models that inherit from neontology's, e.g. here is what I've got to make both fields timezone-aware:

```python
class CustomBaseNode(BaseNode):
    created: AwareDatetime = Field(default_factory=lambda: datetime.now(tz=pytz.utc), json_schema_extra={"set_on_create": True})
    merged: AwareDatetime = Field(default_factory=lambda: datetime.now(tz=pytz.utc), json_schema_extra={"set_on_create": True, "set_on_match": True})
```

However, what you're describing sounds more of a case for serialization to / hydration from the database (adapted from my own code so haven't tested this, but something along those lines):

```python
class CustomBaseNode(BaseNode):
    @field_serializer("created", when_used="unless-none")
    def serialize_created(self, created: datetime, info: FieldSerializationInfo) -> Union[datetime, str]:
        if info.mode == "json":
            return created

        return created.isoformat()

    @field_validator("created", mode="before")
    @classmethod
    def hydrate_created(cls, created: Union[str, datetime], info: ValidationInfo) -> datetime:
        # ... hydrate back from str to datetime
 ```

**Comment by ontolocy** [comment] 2024-09-16 18:18
Hi both,

Thanks for the feedback and comments.

The ideas from @hardchor around subclassing are probably a good place to start. Currently the BaseNode (which inherits from Common model) just uses Python's datetime type for created and merged - you can see how Pydantic handles different inputs for that here: https://docs.pydantic.dev/latest/concepts/conversion_table/ .

If the issue is for retrieving data that's previously been populated, then the model_dump and model_dump_json methods (from Pydantic's BaseModel https://docs.pydantic.dev/latest/concepts/models/#model-methods-and-properties) might be useful.

Longer term, the intent is to remove created and merged as default fields to avoid this kind of problem and give a bit more flexibility.

**Comment by nickknyc** [comment] 2024-09-17 18:44
thank you both @hardchor and @ontolocy 
To be totally honest, I started down the this road - https://docs.pydantic.dev/latest/concepts/serialization/#model-and-field-level-include-and-exclude - and that seemed to work fine. 

The reason for the problem had nothing to do with neo4j or pydantic, it is the Structured Output capability of OpenAI gpt4o and 4o-mini. They only take a subset of datatypes and datetime is not one of them. Also, you cannot have Optional fields. https://platform.openai.com/docs/guides/structured-outputs/introduction So, it was the gpt api that was raising a fuss.

So, you may want to consider
a - making created and merged visible fields - i think they are handy to have.. 
b- then go from datetime to string (iso 8601 - https://www.iso.org/iso-8601-date-and-time-format.html) because I believe that the pydantic-OpenAI Structured Outputs is super powerful and it is super easy to make work... In my case I have a node that has a field that is just a bunch of text and then I have a few string arrays and strings that I start off as being populated with an empty string. I then can pass it to GPT-4o and have the gpt process the text and extract the values I need and tuck them into the appropriate fields and arrays and when I get it back, I just merge it into neo4j. easy peasy. 

thanks again for a super helpful and delightfully simple to understand and use library!

**Comment by ontolocy** [comment] 2024-11-15 09:43
Quick update on this and I'll close the issue.

The latest version (V2) removes the default merged/created fields on BaseNode and BaseRelationship which gives users the flexibility to define them as required. There are some notes on this in the docs https://neontology.readthedocs.io/en/latest/recipes/

V2 also encourages users to explicitly define serialization with Pydantic serializers where you have types which aren't supported by the graph DB driver (or other tooling which uses Pydantic model dump) - https://neontology.readthedocs.io/en/latest/advanced-usage/#type-conversion-serialization .

Shout if you have any more issues!

**Closed by ontolocy** 2024-11-15 09:43 UTC

**Comment by nickknyc** [comment] 2024-11-16 07:17
thanks!!
